-- Inner join
SELECT *
FROM PETS;

SELECT *
FROM PROCEDUREHISTORY;

-- THE NUMBER OF PETS IN THE PETS TABLE COULD BE LESS THAN THE ID'S IN THE PROCEDURE HISTORY TABLE
SELECT *
FROM PROCEDUREHISTORY A
INNER JOIN PETS B
ON A.PETID = B.PETID;
